<DrawerClickableItem@MDNavigationDrawerItem>
    focus_color: app.theme_cls.primary_light
    text_color: app.theme_cls.opposite_bg_dark
    icon_color: app.theme_cls.primary_light
    ripple_color: app.theme_cls.primary_light
    selected_color: [0, 1, 0, 1]


<DrawerLabelItem@MDNavigationDrawerItem>
    text_color: "#4a4939"
    icon_color: "#4a4939"
    focus_behavior: False
    selected_color: "#4a4939"
    _no_ripple_effect: True
